// Auto-generated by /tmp/sfx-manifest-build.py — do not edit by hand.
// Regenerate via the SFX library build pipeline.
//
// The manifest lives at ../../public/sfx/manifest.json (the canonical copy,
// served by Remotion at runtime). This module imports a co-located mirror at
// ./sfx-manifest.json so the TypeScript compiler (rootDir=./src) can resolve
// it. Both files are written together by the build script.

import { staticFile } from 'remotion';
import manifest from './sfx-manifest.json';

export type SfxCategory =
  | 'shutter'
  | 'whoosh'
  | 'impact'
  | 'riser'
  | 'drop'
  | 'transition'
  | 'glitch'
  | 'ui'
  | 'vinyl'
  | 'tape'
  | 'texture';

export type SfxEntry = {
  file: string;
  duration_ms: number;
  peak_db: number | null;
  tags: string[];
  source: string;
  source_id: string;
  license: string;
  attribution: string | null;
  description: string;
  source_url?: string;
};

type CategoryBlock = {
  count: number;
  total_duration_ms: number;
  sounds: SfxEntry[];
};

type Manifest = {
  schema_version: number;
  generated_at: string;
  total_sounds: number;
  total_duration_ms: number;
  categories: Record<SfxCategory, CategoryBlock>;
};

const m = manifest as unknown as Manifest;

/** Raw category map — `sfx.shutter.sounds[0]`, etc. */
export const sfx: Record<SfxCategory, CategoryBlock> = m.categories;

/** All entries flat-mapped, useful for global searches. */
export const allSfx: SfxEntry[] = (Object.values(m.categories) as CategoryBlock[]).flatMap(
  (c) => c.sounds,
);

/** Pick a deterministic SFX from a category by stable seed. */
export function pickSfx(category: SfxCategory, seed: string | number): SfxEntry {
  const list = sfx[category]?.sounds ?? [];
  if (list.length === 0) {
    throw new Error(`No SFX in category: ${category}`);
  }
  const h = typeof seed === 'string' ? hashString(seed) : Math.abs(Math.trunc(seed));
  return list[h % list.length];
}

/** Pick the first SFX in a category whose `tags` include every required tag. */
export function pickSfxByTags(
  category: SfxCategory,
  requiredTags: string[],
  seed: string | number = 0,
): SfxEntry | null {
  const list = sfx[category]?.sounds ?? [];
  const matches = list.filter((s) => requiredTags.every((t) => s.tags.includes(t)));
  if (matches.length === 0) return null;
  const h = typeof seed === 'string' ? hashString(seed) : Math.abs(Math.trunc(seed));
  return matches[h % matches.length];
}

/** Pick an SFX from a category whose duration falls inside `[minMs, maxMs]`. */
export function pickSfxByDuration(
  category: SfxCategory,
  minMs: number,
  maxMs: number,
  seed: string | number = 0,
): SfxEntry | null {
  const list = sfx[category]?.sounds ?? [];
  const matches = list.filter((s) => s.duration_ms >= minMs && s.duration_ms <= maxMs);
  if (matches.length === 0) return null;
  const h = typeof seed === 'string' ? hashString(seed) : Math.abs(Math.trunc(seed));
  return matches[h % matches.length];
}

/** Resolve to a Remotion staticFile URL ready for `<Audio src={...} />`. */
export function sfxUrl(entry: SfxEntry): string {
  return staticFile(`sfx/${entry.file}`);
}

/** Manifest-level metadata (schema, totals, generation date). */
export const sfxMeta = {
  schema_version: m.schema_version,
  generated_at: m.generated_at,
  total_sounds: m.total_sounds,
  total_duration_ms: m.total_duration_ms,
};

// FNV-1a 32-bit string hash — small, fast, good distribution.
function hashString(s: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
