/**
 * studies/audio — waveform visualization synced to a procedurally-generated beat.
 * Uses @remotion/media-utils useAudioData + visualizeAudio.
 *
 * The audio file is generated by scripts/synth_beat.sh into public/synth_beat.wav.
 * Run that first: ./scripts/synth_beat.sh
 */
import React from 'react';
import { useAudioData, visualizeAudio } from '@remotion/media-utils';
import {
  AbsoluteFill,
  Audio,
  Easing,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';

const TRACK = 'synth_beat.wav';

const NUM_SAMPLES = 64;

export const AudioReactive: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();

  const audioData = useAudioData(staticFile(TRACK));
  if (!audioData) {
    return (
      <AbsoluteFill style={{ background: '#0a0a14', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ color: '#9a9ac0', fontFamily: 'SF Pro Display', fontSize: 32 }}>Loading audio...</div>
      </AbsoluteFill>
    );
  }

  const bins = visualizeAudio({
    fps,
    frame,
    audioData,
    numberOfSamples: NUM_SAMPLES,
    optimizeFor: 'speed',
  });

  // Bass = first 8 bins
  const bass = bins.slice(0, 8).reduce((s, v) => s + v, 0) / 8;
  const mid = bins.slice(8, 32).reduce((s, v) => s + v, 0) / 24;
  const high = bins.slice(32, 64).reduce((s, v) => s + v, 0) / 32;

  // Beat-driven pulse on the screen
  const bgIntensity = Math.min(1, bass * 1.4);
  const pulseScale = 1 + bass * 0.06;

  return (
    <AbsoluteFill
      style={{
        background: `radial-gradient(ellipse at center, hsl(${230 + bass * 60}, 60%, ${8 + bgIntensity * 12}%) 0%, #050510 80%)`,
        transform: `scale(${pulseScale})`,
      }}
    >
      {/* Center HUD */}
      <AbsoluteFill style={{ alignItems: 'center', justifyContent: 'center' }}>
        <div
          style={{
            width: 600 + bass * 400,
            height: 600 + bass * 400,
            borderRadius: '50%',
            border: `2px solid hsla(${230 + bass * 60}, 80%, 60%, ${0.4 + bass * 0.6})`,
            boxShadow: `0 0 ${60 + bass * 200}px hsla(${230 + bass * 60}, 80%, 60%, ${bass * 0.5})`,
          }}
        />
        <div
          style={{
            position: 'absolute',
            color: '#fff',
            fontFamily: 'SF Pro Display, sans-serif',
            fontSize: 28,
            letterSpacing: 8,
            textTransform: 'uppercase',
          }}
        >
          <div style={{ color: '#9a9ac0', fontSize: 18, letterSpacing: 6 }}>STUDY 05 · AUDIO</div>
          <div style={{ marginTop: 12, fontWeight: 700, fontSize: 96, letterSpacing: '-0.02em' }}>{bass > 0.18 ? '◉' : '○'}</div>
        </div>
      </AbsoluteFill>

      {/* Spectrum bars at bottom */}
      <div style={{ position: 'absolute', left: 80, right: 80, bottom: 100, height: 320, display: 'flex', alignItems: 'flex-end', gap: 4 }}>
        {bins.map((v, i) => {
          const h = Math.max(2, v * 320);
          const hue = 220 + (i / NUM_SAMPLES) * 80;
          return (
            <div
              key={i}
              style={{
                flex: 1,
                height: h,
                background: `linear-gradient(180deg, hsl(${hue}, 80%, 70%), hsl(${hue}, 80%, 40%))`,
                borderRadius: 2,
                boxShadow: `0 -10px 20px hsla(${hue}, 80%, 60%, 0.4)`,
              }}
            />
          );
        })}
      </div>

      {/* Stat readouts */}
      <div style={{ position: 'absolute', top: 80, left: 80, color: '#fff', fontFamily: 'SF Mono, ui-monospace, monospace', fontSize: 22, lineHeight: 1.6 }}>
        <div>frame   {String(frame).padStart(4, ' ')}</div>
        <div>bass   <span style={{ color: '#5e9eff' }}>{bass.toFixed(3)}</span></div>
        <div>mid    <span style={{ color: '#9b59ff' }}>{mid.toFixed(3)}</span></div>
        <div>high   <span style={{ color: '#ff5e9e' }}>{high.toFixed(3)}</span></div>
      </div>

      {/* Audio is the actual sound + the FFT source */}
      <Audio src={staticFile(TRACK)} volume={1} />
    </AbsoluteFill>
  );
};
